name: Deployment Workflow
on: push
jobs:
  RunLint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run Lint
        run: npm run lint
        working-directory: basic/exercise
  RunTest:
    needs: RunLint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run Test
        run: npm run test
        working-directory: basic/exercise
  RunBuild:
    needs: RunTest
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run Build
        run: npm run build
        working-directory: basic/exercise
  