name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print onformation
        run: echo "${{ toJSON(github) }}"
        working-directory: /basic/learn