name: Basic Le Output
on: [push,workflow_dispatch]
# defaults:
#   run:
#     working-directory: basic/learn
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print information
        run: echo "${{ toJSON(github) }}"