name: Basic Ex Deployment
on: [push, workflow_dispatch]
defaults:
  run:
    working-directory: basic/exercise
jobs:
  RunLint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install package
        run: npm ci
      - name: Run Lint
        run: npm run lint
  RunTest:
    needs: RunLint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install package
        run: npm ci
      - name: Run Test
        run: npm run test
  RunBuild:
    needs: RunTest
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install package
        run: npm ci
      - name: Run Build
        run: npm run build
  